---
name: Build docker image
on:
  workflow_call:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
#    inputs:
#      PUSH_IMAGE:
#        required: false
#        type: boolean
  push:
    tags:
      - 'v*.*.*-rc*'

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract tag name
      id: extract_tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and tag docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push:  true
        tags:  janeliutw/learn-github-actions:${{ steps.extract_tag.outputs.tag }}
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
