---
name: Build docker image
on:
  workflow_call:
#    https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs
#    inputs:
#      PUSH_IMAGE:
#        required: false
#        type: boolean

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

#    - name: Debug secrets
#      run: |
#        echo "DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#
#    - name: Login to DockerHub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_PASSWORD }}

#    - name: Extract tag name
#      id: extract_tag
#      run: |
#        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
#          echo "TAG=latest" >> "$GITHUB_OUTPUT"
#        else
#          echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
#        fi
#
#    - name: Get tag name
#      run: echo "The tag is ${{ steps.extract_tag.outputs.TAG }}"

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: janeliutw/learn-github-actions
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Get tag name
      run: echo "The tag is ${{ steps.meta.outputs.tags }}"

    - name: Should push image
      run: echo "Should push image? ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}"

    - name: Build and tag docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push:  false
#        tags:  janeliutw/learn-github-actions:${{ steps.extract_tag.outputs.TAG }}
        tags:  ${{ steps.meta.outputs.tags }}

