---
name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
    tags:
  pull_request:


jobs:
  run:
    uses: ./.github/workflows/run_python_script.yml
  build:
    needs: [ run ]
    uses: ./.github/workflows/build.yml
#    with:
#      PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}
